import app.default_config as default

DEBUG = default.DEBUG
TESTING = default.TESTING

PROPAGATE_EXCEPTIONS = default.PROPAGATE_EXCEPTIONS
SECRET_KEY = default.SECRET_KEY
SESSION_COOKIE_NAME = default.SESSION_COOKIE_NAME
SESSION_COOKIE_SECURE = default.SESSION_COOKIE_SECURE

APPLICATION_ROOT = default.APPLICATION_ROOT
MAX_CONTENT_LENGTH = default.MAX_CONTENT_LENGTH
JSONIFY_PRETTYPRINT_REGULAR = default.JSONIFY_PRETTYPRINT_REGULAR

DATABASE_USERNAME = 'phobook'
DATABASE_PASSWORD = 'smilu9791!#$%'
DATABASE_URL = 'localhost'
DATABASE_SCHEME_NAME = 'phobook'

DATABASE_CONNECT_URL = 'mysql+pymysql://{}:{}@{}/{}?charset=utf8'.format(\
		DATABASE_USERNAME, DATABASE_PASSWORD, \
		DATABASE_URL, DATABASE_SCHEME_NAME \
	)
DATABASE_SQL_ECHO = False
